import { Address } from 'viem';
import courseJson from './course.json';

/**
 * The CPSC 3640 course deployment the site talks to.
 *
 * `course.json` is generated by `scripts/sync-website-config.mjs --from deployments/<net>.json`;
 * do not edit it by hand. Big numbers (scopes, amounts) are decimal strings there and bigints here.
 */
export type CourseNetwork = 'sepolia' | 'anvil-fork';

export interface CoursePool {
  symbol: string;
  address: Address;
  asset: Address;
  scope: bigint;
  deploymentBlock: bigint;
  decimals: number;
  minimumDepositAmount: bigint;
}

export interface CourseConfig {
  network: CourseNetwork;
  chainId: number;
  entrypoint: Address;
  deploymentBlock: bigint;
  pools: CoursePool[];
  token: { address: Address; symbol: string; decimals: number };
}

export const courseConfig: CourseConfig = {
  network: courseJson.network === 'sepolia' ? 'sepolia' : 'anvil-fork',
  chainId: courseJson.chainId,
  entrypoint: courseJson.entrypoint as Address,
  deploymentBlock: BigInt(courseJson.deploymentBlock),
  pools: courseJson.pools.map((pool) => ({
    symbol: pool.symbol,
    address: pool.address as Address,
    asset: pool.asset as Address,
    scope: BigInt(pool.scope),
    deploymentBlock: BigInt(pool.deploymentBlock),
    decimals: pool.decimals,
    minimumDepositAmount: BigInt(pool.minimumDepositAmount),
  })),
  token: {
    address: courseJson.token.address as Address,
    symbol: courseJson.token.symbol,
    decimals: courseJson.token.decimals,
  },
};

/** True when the site points at a local anvil fork rather than live Sepolia. */
export const isLocalFork = courseConfig.network !== 'sepolia';
